from . import read_input

EXAMPLE = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""


def run_beams(block: str) -> tuple[int, int]:
    cur_beams: dict[int, int] = {}
    splits = 0
    for row in block.splitlines():
        if len(cur_beams) == 0:
            cur_beams = {i: 1 for i, val in enumerate(row) if val == "S"}
        else:
            new_beams: dict[int, int] = {}
            for beam, beam_value in cur_beams.items():
                if row[beam] == ".":
                    new_beams[beam] = new_beams.get(beam, 0) + beam_value
                elif row[beam] == "^":
                    new_beams[beam - 1] = new_beams.get(beam - 1, 0) + beam_value
                    new_beams[beam + 1] = new_beams.get(beam + 1, 0) + beam_value
                    splits += 1
            cur_beams = new_beams
    return splits, sum(cur_beams.values())


assert run_beams(EXAMPLE) == (21, 40)
print(run_beams(read_input("07")))
